show_on:
  default: homepage
  type: enum
  choices:
    - homepage
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - below-site-header

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out

image_1:
  default: ""
  description: image for the 1st announcement item in the carousel
  type: "upload"
image_2:
  default: ""
  description: image for the 2nd announcement item in the carousel
  type: "upload"
image_3:
  default: ""
  description: image for the 3rd announcement item in the carousel
  type: "upload"
